name: Update Monsters Index

on:
  push:
    paths:
      - 'data/*.json'
    paths-ignore:
      - 'data/monsters.json'

jobs:
  update-index:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Generate monsters.json
        run: |
          node <<'JS'
          const fs = require('fs');
          const path = require('path');

          const dataDir = path.join(process.cwd(), 'data');
          const files = fs.readdirSync(dataDir)
            .filter(f => f.endsWith('.json') && f !== 'monsters.json');

          const monsters = files.map(f => {
            const content = JSON.parse(fs.readFileSync(path.join(dataDir, f)));
            const displayName = content.name || path.basename(f, '.json');
            return {
              ...content,                // include all original monster data
              _file: f,                  // helper for links
              _displayName: displayName, // helper for display headings
              name: displayName,         // keep top-level name
              file: f                     // original file reference
            };
          });

          fs.writeFileSync(
            path.join(dataDir, 'monsters.json'),
            JSON.stringify(monsters, null, 2)
          );
          console.log(`Updated monsters.json with ${monsters.length} entries.`);
          JS

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/monsters.json
          git commit -m "Update monsters.json" || echo "No changes to commit"
          git push
