name: Update index.json

on:
  push:
    paths:
      - "data/*.json"
  workflow_dispatch:

permissions:
  contents: write   # <-- allow pushing changes back to the repo

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          persist-credentials: true  # keeps token for pushing

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Generate index.json
        run: node .github/scripts/generate-index.js

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add data/index.json
          git commit -m "Update index.json [skip ci]" || echo "No changes to commit"
          git push
